// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBUhZ9TzzllA6L1OAKTehpSkd8CCeZ6OM',
    appId: '1:2569758667:web:20ee8b9322e01e27e0b84e',
    messagingSenderId: '2569758667',
    projectId: 'e-commerce-fdc56',
    authDomain: 'e-commerce-fdc56.firebaseapp.com',
    storageBucket: 'e-commerce-fdc56.firebasestorage.app',
    measurementId: 'G-JB1BMK3N0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPBbGw4kimtU0BDvaXTJJJa4VPXLCfog',
    appId: '1:2569758667:android:147ed989f8ad0c07e0b84e',
    messagingSenderId: '2569758667',
    projectId: 'e-commerce-fdc56',
    storageBucket: 'e-commerce-fdc56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK8OjnbgccEg8HqoNDjg1-O636kjntwtI',
    appId: '1:2569758667:ios:b8e1b05eae2eccf1e0b84e',
    messagingSenderId: '2569758667',
    projectId: 'e-commerce-fdc56',
    storageBucket: 'e-commerce-fdc56.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK8OjnbgccEg8HqoNDjg1-O636kjntwtI',
    appId: '1:2569758667:ios:b8e1b05eae2eccf1e0b84e',
    messagingSenderId: '2569758667',
    projectId: 'e-commerce-fdc56',
    storageBucket: 'e-commerce-fdc56.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBUhZ9TzzllA6L1OAKTehpSkd8CCeZ6OM',
    appId: '1:2569758667:web:b5f1ae8a82432726e0b84e',
    messagingSenderId: '2569758667',
    projectId: 'e-commerce-fdc56',
    authDomain: 'e-commerce-fdc56.firebaseapp.com',
    storageBucket: 'e-commerce-fdc56.firebasestorage.app',
    measurementId: 'G-0K9ZY5L386',
  );
}
